// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/manuhdez/transactions-api/internal/users/domain/event"
	mock "github.com/stretchr/testify/mock"
)

// Bus is an autogenerated mock type for the Bus type
type Bus struct {
	mock.Mock
}

// Listen provides a mock function with given fields:
func (_m *Bus) Listen() {
	_m.Called()
}

// Publish provides a mock function with given fields: ctx, _a1
func (_m *Bus) Publish(ctx context.Context, _a1 event.Event) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Event) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: _a0, _a1
func (_m *Bus) Subscribe(_a0 event.Type, _a1 event.Handler) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewBus interface {
	mock.TestingT
	Cleanup(func())
}

// NewBus creates a new instance of Bus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBus(t mockConstructorTestingTNewBus) *Bus {
	mock := &Bus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
