// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Hasher is an autogenerated mock type for the HashService type
type Hasher struct {
	mock.Mock
}

type Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Hasher) EXPECT() *Hasher_Expecter {
	return &Hasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: hashed, password
func (_m *Hasher) Compare(hashed string, password string) error {
	ret := _m.Called(hashed, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashed, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Hasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type Hasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashed string
//   - password string
func (_e *Hasher_Expecter) Compare(hashed interface{}, password interface{}) *Hasher_Compare_Call {
	return &Hasher_Compare_Call{Call: _e.mock.On("Compare", hashed, password)}
}

func (_c *Hasher_Compare_Call) Run(run func(hashed string, password string)) *Hasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Hasher_Compare_Call) Return(_a0 error) *Hasher_Compare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Hasher_Compare_Call) RunAndReturn(run func(string, string) error) *Hasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with given fields: value
func (_m *Hasher) Hash(value string) (string, error) {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(value)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type Hasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - value string
func (_e *Hasher_Expecter) Hash(value interface{}) *Hasher_Hash_Call {
	return &Hasher_Hash_Call{Call: _e.mock.On("Hash", value)}
}

func (_c *Hasher_Hash_Call) Run(run func(value string)) *Hasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Hasher_Hash_Call) Return(_a0 string, _a1 error) *Hasher_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Hasher_Hash_Call) RunAndReturn(run func(string) (string, error)) *Hasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
