// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

type TokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenService) EXPECT() *TokenService_Expecter {
	return &TokenService_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: userId
func (_m *TokenService) CreateToken(userId string) (string, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenService_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type TokenService_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - userId string
func (_e *TokenService_Expecter) CreateToken(userId interface{}) *TokenService_CreateToken_Call {
	return &TokenService_CreateToken_Call{Call: _e.mock.On("CreateToken", userId)}
}

func (_c *TokenService_CreateToken_Call) Run(run func(userId string)) *TokenService_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenService_CreateToken_Call) Return(_a0 string, _a1 error) *TokenService_CreateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenService_CreateToken_Call) RunAndReturn(run func(string) (string, error)) *TokenService_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *TokenService) ValidateToken(token string) bool {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// TokenService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type TokenService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *TokenService_Expecter) ValidateToken(token interface{}) *TokenService_ValidateToken_Call {
	return &TokenService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *TokenService_ValidateToken_Call) Run(run func(token string)) *TokenService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenService_ValidateToken_Call) Return(_a0 bool) *TokenService_ValidateToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenService_ValidateToken_Call) RunAndReturn(run func(string) bool) *TokenService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
