inpackage: False
outpkg: mocks
dir: test/mocks
filename: "{{.PackageName}}_{{.InterfaceName | snakecase | lower }}.go"
mockname: "{{.PackageName | firstUpper }}{{.InterfaceName}}"

packages:
  github.com/manuhdez/transactions-api/internal/accounts/internal/domain/account:
    interfaces:
      Repository:
      Finder:

  github.com/manuhdez/transactions-api/internal/accounts/internal/domain/transaction:
    interfaces:
      Repository:
      Transferer:
        config:
          filename: transferer.go
          mockname: Transferer
