version: '3.9'
services:
  accounts:
    build:
      context: docker/app
    working_dir: /internal/accounts
    volumes:
      - ./internal:/internal
    env_file:
      - .env
    environment:
      APP_PORT: "8081"
    ports:
      - "8081:8081"
    depends_on:
      - accounts_db

  transactions:
    build:
      context: docker/app
    working_dir: /internal/transactions
    volumes:
      - ./internal:/internal
    env_file:
      - .env
    environment:
      APP_PORT: "8082"
    ports:
      - "8082:8082"
    depends_on:
      - transactions_db

  # Database for accounts service
  accounts_db:
    image: mysql:8
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - ./sql/accounts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - accounts_data:/var/lib/mysql
    ports:
      - "3306:${MYSQL_PORT_ACCOUNTS}"
    restart: unless-stopped

 # Database for transactions service
  transactions_db:
    image: mysql:8
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - ./sql/transactions/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - transactions_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT_TRANSACTIONS}:3306"
    restart: unless-stopped

volumes:
  accounts_data:
  transactions_data:
