// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"

	account "github.com/manuhdez/transactions-api/internal/transactions/domain/account"

	mock "github.com/stretchr/testify/mock"
)

// AccountCreator is an autogenerated mock type for the AccountCreator type
type AccountCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *AccountCreator) Create(_a0 context.Context, _a1 account.Account) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, account.Account) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountCreator creates a new instance of AccountCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountCreator {
	mock := &AccountCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
