// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/manuhdez/transactions-api/internal/transactions/domain/event"
	mock "github.com/stretchr/testify/mock"

	transaction "github.com/manuhdez/transactions-api/internal/transactions/domain/transaction"
)

// ServiceWithdrawer is an autogenerated mock type for the Withdrawer type
type ServiceWithdrawer struct {
	mock.Mock
}

type ServiceWithdrawer_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceWithdrawer) EXPECT() *ServiceWithdrawer_Expecter {
	return &ServiceWithdrawer_Expecter{mock: &_m.Mock}
}

// PullEvents provides a mock function with given fields:
func (_m *ServiceWithdrawer) PullEvents() []event.Event {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PullEvents")
	}

	var r0 []event.Event
	if rf, ok := ret.Get(0).(func() []event.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	return r0
}

// ServiceWithdrawer_PullEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullEvents'
type ServiceWithdrawer_PullEvents_Call struct {
	*mock.Call
}

// PullEvents is a helper method to define mock.On call
func (_e *ServiceWithdrawer_Expecter) PullEvents() *ServiceWithdrawer_PullEvents_Call {
	return &ServiceWithdrawer_PullEvents_Call{Call: _e.mock.On("PullEvents")}
}

func (_c *ServiceWithdrawer_PullEvents_Call) Run(run func()) *ServiceWithdrawer_PullEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceWithdrawer_PullEvents_Call) Return(_a0 []event.Event) *ServiceWithdrawer_PullEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceWithdrawer_PullEvents_Call) RunAndReturn(run func() []event.Event) *ServiceWithdrawer_PullEvents_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: _a0, _a1
func (_m *ServiceWithdrawer) Withdraw(_a0 context.Context, _a1 transaction.Transaction) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.Transaction) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceWithdrawer_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type ServiceWithdrawer_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 transaction.Transaction
func (_e *ServiceWithdrawer_Expecter) Withdraw(_a0 interface{}, _a1 interface{}) *ServiceWithdrawer_Withdraw_Call {
	return &ServiceWithdrawer_Withdraw_Call{Call: _e.mock.On("Withdraw", _a0, _a1)}
}

func (_c *ServiceWithdrawer_Withdraw_Call) Run(run func(_a0 context.Context, _a1 transaction.Transaction)) *ServiceWithdrawer_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transaction.Transaction))
	})
	return _c
}

func (_c *ServiceWithdrawer_Withdraw_Call) Return(_a0 error) *ServiceWithdrawer_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceWithdrawer_Withdraw_Call) RunAndReturn(run func(context.Context, transaction.Transaction) error) *ServiceWithdrawer_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceWithdrawer creates a new instance of ServiceWithdrawer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceWithdrawer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceWithdrawer {
	mock := &ServiceWithdrawer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
