inpackage: False
outpkg: mocks
dir: test/mocks
filename: "{{.PackageName}}_{{.InterfaceName | snakecase | lower }}.go"
mockname: "{{.PackageName | firstUpper }}{{.InterfaceName}}"

packages:
  github.com/manuhdez/transactions-api/internal/transactions/app/service:
    interfaces:
      Depositer:
      Withdrawer:
      Transferer: