// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/manuhdez/transactions-api/internal/transactions/controllers"
	"github.com/manuhdez/transactions-api/internal/transactions/di"
	"net/http"
)

// Injectors from wire.go:

func InitServer() *http.ServeMux {
	statusController := controllers.NewStatusController()
	serveMux := di.NewServer(statusController)
	return serveMux
}
