// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/manuhdez/transactions-api/internal/users/application/service"
	"github.com/manuhdez/transactions-api/internal/users/container"
	"github.com/manuhdez/transactions-api/internal/users/http/api"
	"github.com/manuhdez/transactions-api/internal/users/http/api/v1/controller"
	"github.com/manuhdez/transactions-api/internal/users/infra"
	"github.com/manuhdez/transactions-api/shared/config"
)

// Injectors from wire.go:

func Init() container.App {
	healthCheck := controller.NewHealthCheck()
	dbConfig := config.NewDBConfig()
	db := config.NewDBConnection(dbConfig)
	userMysqlRepository := infra.NewUserMysqlRepository(db)
	bcryptHashService := infra.NewBcryptService()
	rabbitEventBus := infra.NewRabbitEventBus()
	registerUser := service.NewRegisterUserService(userMysqlRepository, bcryptHashService, rabbitEventBus)
	controllerRegisterUser := controller.NewRegisterUserController(registerUser)
	loginService := service.NewLoginService(userMysqlRepository, bcryptHashService)
	jwtService := infra.NewJWTService()
	login := controller.NewLoginController(loginService, jwtService)
	usersRetriever := service.NewUsersRetrieverService(userMysqlRepository)
	getAllUsers := controller.NewGetAllUsersController(usersRetriever)
	router := api.NewRouter(healthCheck, controllerRegisterUser, login, getAllUsers)
	app := container.NewApp(router, rabbitEventBus)
	return app
}
